### ISSUE TITLE
Citation style

### ISSUE THREAD

**Issue by dowobeha** [authorofnaught/thesis#1]
Use ACL citation styles. This can be accomplished, among other ways, by use of the natbib package (see http://merkel.texture.rocks/Latex/natbib.php).

> We direct the reader to [Trembly and Muggs, 1998], [Childish and Puerile, 2007], and [Presso, 2010].

The above should instead be:

> We direct the reader to Trembly and Muggs (1998), Childish and Puerile (2007), and Presso (2010).

**Comment by authorofnaught** [comment]
per suggestion [here](https://clear.colorado.edu/CompSemWiki/index.php/Adding_ACL_Style_Citations), the following two lines were added to thesis.tex, which appear to have addressed the issue:
\usepackage[round]{natbib}
\bibliographystyle{plainnat}
