### ISSUE TITLE
Bibliography entries

### ISSUE THREAD

**Issue by dowobeha** [authorofnaught/thesis#2]
Current bibliography entries have extra bracketed name at the beginning of the lines:

> [Childish and Puerile, 2007] Childish, H. and Puerile, G. (2007). Coffee tolerance of middle schoolers. Impure Science, 5(2):58–71.

The [Childish and Puerile, 2007] should be removed.

**Comment by authorofnaught** [comment]
This issue appears to have been fixed by the same lines which fixed [issue#1](https://github.com/authorofnaught/thesis/issues/1).
